# Generated by Django 4.1.2 on 2023-06-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_atencion',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.estado_atencion'),
            preserve_default=False,
        ),
    ]
