# Generated by Django 4.1.2 on 2023-06-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_estado_atencion_atencion_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=15)),
                ('apellido_contacto', models.CharField(max_length=50)),
                ('fecha_contacto', models.DateField()),
                ('comentario_contacto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_atencion',
            fields=[
                ('id_tipo_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_atencion', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='id_estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='taller.estado_atencion'),
        ),
    ]
