# Generated by Django 4.1.2 on 2023-06-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_info_contacto_tipo_atencion_alter_atencion_id_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='id_tipo_atencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.tipo_atencion'),
            preserve_default=False,
        ),
    ]
