# Generated by Django 4.1.2 on 2023-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_atencion_id_tipo_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_contacto',
            name='correo_contacto',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
